# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoinfo',
            name='description',
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
