# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('youtube_id', models.CharField(max_length=100, unique=True)),
                ('url_thumbnail', models.URLField(blank=True, max_length=300)),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='VideoInfo',
        ),
    ]
