# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170223_1209'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='bookmark_videos',
            field=models.ManyToManyField(blank=True, through='member.BookmarkVideo', to='video.Video'),
        ),
    ]
